:: generated by pwshc, do not edit
:: <# BEGIN POWERSHELL AS BATCH HEADER
@ECHO OFF
copy %~s0 %~s0.ps1 >nul
PowerShell.exe -ExecutionPolicy Unrestricted -NoProfile -Command function :: {}; %~s0.ps1 '%1' '%2'


GOTO :EOF

:: END POWERSHELL AS BATCH HEADER #>
. {

# hello world
Write-Host "Hello, World!"
# Non-ASCII characters
Write-Host "§≥§Û§À§¡§œ°¢ ¿ΩÁ£°"
# pause
Read-Host -Prompt "Press Enter to exit"

} @Args