:: <# BEGIN POWERSHELL AS BATCH HEADER
:: generated by pwshc (https://github.com/Koswu/pwshc), do not edit
@ECHO OFF
del %~s0.ps1 >nul 2>&1  

net session >nul 2>&1
if %errorlevel% neq 0 (
    echo "Reruning as administrator..."
    powershell -Command "Start-Process '%~f0' -Verb runAs"
    exit /b
)

copy %~s0 %~s0.ps1 >nul 
PowerShell.exe -ExecutionPolicy Unrestricted -NoProfile -Command function :: {}; %~s0.ps1 %* 
del %~s0.ps1 >nul 
GOTO :EOF 
:: END POWERSHELL AS BATCH HEADER #>
. {
# hello world
Write-Host "Hello, World!"
# Non-ASCII characters
Write-Host "§≥§Û§À§¡§œ°¢ ¿ΩÁ£°"
# pause
Read-Host -Prompt "Press Enter to exit"
} @Args